# Generated by Django 2.1.7 on 2019-05-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
